Sprint 3
pushka-pashka/middle.messenger.praktikum.yandex pull request #4
Opened 2023-02-13 18:30 UTC by pushka-pashka

2023-02-14 18:36 UTC, maks88sgt requested changes
Привет. У меня возникли проблемы с запуском проекта. Первая проблема - package-lock.json файл, как правило его не стоит коммитить, если используются фиксированные версии. Проблема была в том, что в нем зафиксирована какая то зависимость, которая у меня устанавливалась с ошибкой. После того как я удалил package-lock зависимости встали, но проект не запускался из-за ошибок parcel. Проблему удалось решить повысив версию. Однако после этих изменений приложение работало некорректно (неправильно собирался код для шаблонизатора). В итоге смотрел функционал в задеплоенной версии и там тоже не все работает как нужно - при переключении между чатами содержимое чата не обновляется, при перезагрузке страницы на странице редактирования профиля приложение падает с ошибкой. Отправка сообщений по вебсокетам не работает. По чистоте кода и архитектуре в целом особых вопросов нет, но нужно сделать чтобы приложение заработало.

2023-02-14 18:36 UTC, maks88sgt commented on src/components/button/button.ts
> +    // );
Закомментированный код лучше сразу удалять из проекта, он как правило не несет никакой нагрузке а только захламляет код.

2023-02-14 18:36 UTC, maks88sgt commented on src/components/chatsList/chatsList.ts
> +interface IChatListProps {
Использование префиксов считается довольно устаревшей практикой. Это венгерская нотация, которая сейчас редко используется. Безусловно соглашения о коде зависят от конкретной команды

2023-02-27 16:34 UTC, pushka-pashka commented
> Привет. У меня возникли проблемы с запуском проекта. Первая проблема - package-lock.json файл, как правило его не стоит коммитить, если используются фиксированные версии.

Привет, @maks88sgt . 
В самом первом ПР, ревьювер наоброт советовал использовать фиксированные версии в связке с package-lock.json 
Так как все-таки более правильно? 
И как можно точно убедиться, что код из репозитория без ошибок соберется у другого?

2023-02-27 19:40 UTC, maks88sgt commented
Привет. Вот здесь например можно прочитать про то зачем нужен lock файл https://medium.com/nuances-of-programming/файл-package-lock-json-полное-руководство-cc0136330db6. В случае если ты фиксируешь версии зависимостей, то есть используешь только строго определенные версии, то он не нужен.
На самом деле нет однозначного ответа что правильнее. Все зависит от соглашений в команде и т.д.. А по поводу одинаковой среды - это извечная проблема при разработке и например Docker контейнеры решают большинство кейсов.

2023-03-02 19:17 UTC, maks88sgt approved these changes
Работу принял. Успехов на курсе!

2023-03-02 20:23 UTC, merged